# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07service\"\x17\n\tMyRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x1a\n\nMyResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"!\n\x10SubscribeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\",\n\x06Update\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x32{\n\tMyService\x12\x33\n\x08MyMethod\x12\x12.service.MyRequest\x1a\x13.service.MyResponse\x12\x39\n\tSubscribe\x12\x19.service.SubscribeRequest\x1a\x0f.service.Update0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MYREQUEST']._serialized_start=26
  _globals['_MYREQUEST']._serialized_end=49
  _globals['_MYRESPONSE']._serialized_start=51
  _globals['_MYRESPONSE']._serialized_end=77
  _globals['_SUBSCRIBEREQUEST']._serialized_start=79
  _globals['_SUBSCRIBEREQUEST']._serialized_end=112
  _globals['_UPDATE']._serialized_start=114
  _globals['_UPDATE']._serialized_end=158
  _globals['_MYSERVICE']._serialized_start=160
  _globals['_MYSERVICE']._serialized_end=283
# @@protoc_insertion_point(module_scope)
