replicaCount: 1

image:
  repository: orders-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: orders-svc-s14
  type: ClusterIP
  port: 8222

k8s:
  app: orders-app
  container: orders-container

extra_field:
  priority: 3

project_code: orders-s14

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nameOverride: ""
fullnameOverride: ""