replicaCount: 1

image:
  repository: orders-app
  tag: dev
  pullPolicy: Always

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

extra_field:
  priority: 1